### ISSUE TITLE
What are the legalities of using those icons?

### ISSUE THREAD

**Issue by ToddStarbuck** [cftarbay/VTM-V5-Dice-Roller#20]
Hello Clarice!
I want to use the official icons for some merch I'd like to sell.
Did you need permission to use them?  How did you go about that?

I see your roller get lots of use on Vampires of Pittsburgh. 

Todd

**Comment by cftarbay** [comment]
Hi Todd!

I apologize but I'm not really in a position to give you any advice about
this. The roller is completely non-commercial, and I don't create any merch
myself.

Good luck with the merch, though! :)
